global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using Dungeon_Crawl.src.Monsters;
global using Dungeon_Crawl.src.Utils;
global using Dungeon_Crawl.src.StaticObjects;
global using Dungeon_Crawl.src.Objects;